######################################################################
##
## Filename: lupa_tstbc.udo
## Created on: Thu Aug 04 3:07:08 PM Eastern Daylight Time 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
