######################################################################
##
## Filename: lupa_tstbc.udo
## Created on: Fri Jan 15 4:06:20 PM Eastern Standard Time 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
