######################################################################
##
## Filename: spi_upload.udo
## Created on: Mon Jan 18 2:45:48 PM Eastern Standard Time 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
